server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-series
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: seriesdevmongo
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
