server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: series-service
  data:
    mongodb:
      username: usr-series
      password: pwd-series
      database: seriesdevmongo
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka